// Writes src/pool/engine/version.js: a hash of every other engine file. The
// browser sends it when it joins a room and the Worker turns away a page
// built from different rules or physics (a deploy of one side but not yet
// the other). `npm test` fails if the file is stale.
//   node scripts/pool-version.mjs          write it
//   node scripts/pool-version.mjs --check  exit 1 if it is out of date
import { createHash } from 'node:crypto';
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const dir = resolve(import.meta.dirname, '../src/pool/engine');
const files = readdirSync(dir).filter((f) => f.endsWith('.js') && f !== 'version.js').sort();
const hash = createHash('sha256');
for (const f of files) hash.update(f + '\n' + readFileSync(resolve(dir, f), 'utf8').replace(/\r\n/g, '\n'));
const version = hash.digest('hex').slice(0, 12);
const text = `// Generated by scripts/pool-version.mjs from the other engine files. Do not edit.\nexport const ENGINE_VERSION = '${version}';\n`;
const path = resolve(dir, 'version.js');
if (process.argv.includes('--check')) {
  let current = '';
  try {
    current = readFileSync(path, 'utf8').replace(/\r\n/g, '\n');
  } catch {}
  if (current !== text) {
    console.error('src/pool/engine/version.js is stale: run node scripts/pool-version.mjs');
    process.exit(1);
  }
} else {
  writeFileSync(path, text);
  console.log('ENGINE_VERSION', version);
}
